### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by kooku0** [CodeSoom/project-react-5-kooku94#1]
## 1. 이 앱을 언제 사용하나요?
- 사진 올리고 친구들과 공유
## 2. 구체적인 사례는 무엇인가요?
- 인스타그램
- ticktock
- youtube shortcut
## 3. 이번주가 지나면 사용자는 무엇을 할 수 있나요?
- 타이틀을 볼 수 있습니다.
- 배포된 앱을 볼 수 있습니다.
## 4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- [x] 프로젝트 셋팅
- [x] 유닛 테스트 환경 구축
- [x] eslint 셋팅
- [x] husky 적용
- [x] e2e 테스트 셋팅
- [x] hosting

**Comment by kooku94** [comment]
계속 고민했었는데, 이제 시작하겠습니다!!
